# Generated by Django 5.0.6 on 2024-06-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('SCIENCE_FICTION', 'Science Fiction'), ('FANTASY', 'Fantasy')]),
        ),
        migrations.AlterField(
            model_name='movies',
            name='produced_by',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='stars',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='writers',
            field=models.CharField(),
        ),
    ]
