# Generated by Django 5.0.6 on 2024-06-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movies_description_alter_movies_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.CharField(choices=[('U', 'U'), ('PG', 'PG'), ('12', '12'), ('15', '15'), ('18', '18')], default='U'),
        ),
    ]
