# Generated by Django 5.0.6 on 2024-06-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image_card',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image_cover',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='video',
            field=models.FileField(upload_to='media/'),
        ),
    ]
