# Generated by Django 5.0.6 on 2024-06-23 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_movielist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='produced_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('U', 'U'), ('PG', 'PG'), ('12', '12'), ('15', '15'), ('18', '18')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.CharField(max_length=255),
        ),
    ]
